"""engine/verbs -- generic, game-agnostic MUD command handlers.

This package is the engine side of the commands.py split (see that module's
docstring, and command_support.py's, for the full rationale). Everything
here is a plain MUD-engine verb -- movement, looking, inventory, talking,
who's online, the clock, help/commands listings, and the bug/suggestion
report pipeline -- that would make sense in ANY game built on this engine,
not just SUPERS.

`ENGINE_COMMANDS` is a verb -> (handler, help_text) dict, exactly like the
old commands.py `COMMANDS` table but scoped to just these engine-generic
verbs. `commands.py` merges this with `supers.verbs.SUPERS_COMMANDS` to
build the real dispatch table.

Hard rule (AGENTS.md / two-repo purity Phase 2): this package must NOT
import the SUPERS game package at all -- not at module level, and not with
a LAZY, function-local import either. An earlier pass allowed a handler
body to reach into SUPERS with a function-local import for a bit of game
flavor; Phase 2 forbids that outright (see basic.py's module docstring) --
those flavor sites now go through `engine.hooks` instead, which SUPERS
wires up at boot without this package ever needing to know SUPERS exists.
"""
from .channels import cmd_chans, cmd_mute, cmd_mutes, cmd_unmute
from .basic import (
    cmd_account,
    cmd_alias,
    cmd_brief,
    cmd_bug,
    cmd_bugs,
    cmd_changes,
    cmd_color,
    cmd_commands,
    cmd_config,
    cmd_date,
    cmd_drop,
    cmd_emote,
    cmd_enter,
    cmd_examine,
    cmd_exit_zone,
    cmd_exits,
    cmd_follow,
    cmd_get,
    cmd_give,
    cmd_go_in,
    cmd_go_out,
    cmd_group,
    cmd_party,
    cmd_hdelete,
    cmd_hedit,
    cmd_hrefresh,
    cmd_hunder,
    cmd_hnews,
    cmd_help,
    cmd_gmhelp,
    cmd_helpsubmit,
    cmd_afk,
    cmd_idlemode,
    cmd_ideas,
    cmd_inventory,
    cmd_look,
    cmd_map,
    cmd_mpkg,
    cmd_bigmap,
    cmd_nearby,
    cmd_zone,
    cmd_ooc,
    cmd_questions,
    cmd_answers,
    cmd_replay,
    cmd_open,
    cmd_prompt,
    cmd_quit,
    cmd_logout,
    cmd_reports,
    cmd_resolve,
    cmd_save,
    cmd_say,
    cmd_smote,
    cmd_search,
    cmd_setpass,
    cmd_sit,
    cmd_stand,
    cmd_suggest,
    cmd_tell,
    cmd_ooctell,
    cmd_reply,
    cmd_time,
    cmd_timeformat,
    cmd_typo,
    cmd_typos,
    cmd_unfollow,
    cmd_who,
)
from engine.verbs.player_queries import (
    cmd_queries,
    cmd_query,
    cmd_queryclose,
    cmd_querycomment,
    cmd_querylist,
    cmd_queryread,
)
from engine.pager import cmd_more, cmd_stop

# Verb -> (handler, help_text). See commands.py's COMMANDS docstring for why
# the help_text lives right next to the handler instead of somewhere else.
ENGINE_COMMANDS = {
    "look":      (cmd_look,      "look at the room, or look <name> / look me for a description"),
    "l":         (cmd_look,      "look at the room, or look <name> / look me for a description"),
    "nearby":    (cmd_nearby,    "list people in the room (same as look people; see help formatting)"),
    "exits":     (cmd_exits,     "list doors from this room (leave / exit car climb out of a ride; see 'help enter')"),
    "sit":       (cmd_sit,       "sit down where you are (flavor; see also stand)"),
    "stand":     (cmd_stand,     "stand up from sitting (flavor; see also sit)"),
    "search":    (cmd_search,    "feel for secret exits in this room (see 'help search')"),
    "map": (cmd_map, "local ASCII map on look / map; map big = atlas camera that fits your screen (see 'help map')"),
    "zone": (cmd_zone, "nearby zone bearings on overland (alias of map zone; see 'help map')"),
    "bigmap":    (cmd_bigmap,    "overland atlas camera (same as map big; see 'help map')"),
    # Bare ``atlas`` is owned by SUPERS (America map; drive travels). Keep
    # bigmap / map big for the generic atlas camera on any overland.
    "examine":   (cmd_examine,   "look closely at an item or person (try examine sword or examine me)"),
    "exa":       (cmd_examine,   "look closely at an item or person (try examine sword or examine me)"),
    "ex":        (cmd_examine,   "look closely at an item or person (try examine sword or examine me)"),
    "enter":     (cmd_enter,     "enter <zone> from an overland gateway (see 'help enter')"),
    "exit":      (cmd_exit_zone, "leave a pocket zone from its entry mouth (see 'help enter')"),
    "in":        (cmd_go_in,     "go in through a nested indoor exit"),
    "out":       (cmd_go_out,    "go out through a nested indoor exit"),
    "leave":     (cmd_go_out,    "go out through a nested indoor exit"),
    "get":       (cmd_get,       "pick up an item (get <name>|all|10 from backpack; get all.<name> from 2.backpack)"),
    "take":      (cmd_get,       "pick up an item (get <name>|all|all.<name>; get all.<name> from 2.backpack)"),
    "drop":      (cmd_drop,      "drop a carried item (drop <name>|all|all.<name>)"),
    "give":      (cmd_give,      "hand items or pocket cash to someone here (give <item>|$N to <name>)"),
    "hand":      (cmd_give,      "hand items or pocket cash to someone here (give <item>|$N to <name>)"),
    "open":      (cmd_open,      "open a structure door (open north) or force open a locked container"),
    "inventory": (cmd_inventory, "list what you are carrying"),
    "inv":       (cmd_inventory, "list what you are carrying"),
    "i":         (cmd_inventory, "list what you are carrying"),
    "say":       (cmd_say,       "speak aloud to everyone in the room; bare say replays room speech"),
    "'":         (cmd_say,       "speak aloud to everyone in the room; bare say replays room speech"),
    "emote":     (cmd_emote,     "free-form third-person action; bare emote replays recent poses"),
    "em":        (cmd_emote,     "free-form third-person action; bare emote replays recent poses"),
    "smote":     (cmd_smote,     "third-person action; :grins shorthand (see 'help emote')"),
    "tell":      (cmd_tell,      "private IC message anywhere; bare tell replays recent tells (see 'help tell')"),
    "whisper":   (cmd_tell,      "private IC message anywhere; bare tell replays recent tells (see 'help tell')"),
    "ooctell":   (cmd_ooctell,   "private OOC message anywhere; bare ooctell replays recent OOC tells (see 'help ooctell')"),
    "otell":     (cmd_ooctell,   "alias: ooctell (see 'help ooctell')"),
    "reply":     (cmd_reply,     "tell back to whoever last told you (reply hi)"),
    "r":         (cmd_reply,     "short for reply -- tell back to whoever last told you"),
    "ooc":       (cmd_ooc,       "global OOC chat; bare ooc numbers the last 20"),
    "questions": (cmd_questions, "global player-help questions; question is the same verb; bare questions numbers recent lines"),
    "question":  (cmd_questions, "alias: questions (see 'help questions')"),
    "answers":   (cmd_answers,   "helper answers net; bare answers numbers recent lines (helpers only)"),
    "replay":    (cmd_replay,    "replay ooc 12 or replay questions 12 for one numbered line"),
    "query":     (cmd_query,     "open a helper ticket when nobody is online (see help query)"),
    "queries":   (cmd_queries,   "helpers: list open player query tickets"),
    "querylist": (cmd_querylist, "helpers: list open player query tickets"),
    "queryread": (cmd_queryread, "read one query thread by id"),
    "querycomment": (cmd_querycomment, "add a comment to a query thread"),
    "queryclose": (cmd_queryclose, "helpers: close a resolved query ticket"),
    "mute":      (cmd_mute,      "ignore an account on OOC/public channels (not IC say/tell; see help mute)"),
    "unmute":    (cmd_unmute,    "clear an OOC/public-channel mute (see help mute)"),
    "mutes":     (cmd_mutes,     "list accounts you mute on OOC/public channels"),
    "chans":     (cmd_chans,     "create or manage player public chat channels (see help chans)"),
    "follow":    (cmd_follow,    "follow <name> when they move; bare follow stops (see 'help follow')"),
    "unfollow":  (cmd_unfollow,  "stop following whoever you are following"),
    "group":     (cmd_group,     "party menu + focus + row (see 'help group')"),
    "party":     (cmd_party,     "invite/accept party; leader pulls dungeon runs (see 'help party')"),
    "idlemode":  (cmd_idlemode,  "act as an Echo while still logged in (see 'help idlemode')"),
    "idle":      (cmd_idlemode,  "short for idlemode -- bare toggles (see 'help idlemode')"),
    "afk":       (cmd_afk,       "RP pause without Cadence (see 'help afk')"),
    "setpass":   (
        cmd_setpass,
        "setpass <current> <new> -- change login password (min 6; GMs need symbols)",
    ),
    "save":      (cmd_save,      "save your character now (see 'help save')"),
    "who":       (cmd_who,       "list players online"),
    "more":      (cmd_more,      "show the next page of a long dump (see 'help more')"),
    "stop":      (cmd_stop,      "discard remaining paged text (see 'help more')"),
    "time":      (cmd_time,      "show the in-game clock, day period, and season"),
    "timeformat": (cmd_timeformat, "clock display: timeformat 12|24 (see 'help calendar')"),
    "color":     (cmd_color,     "ANSI color on|off; bare toggles (see 'help formatting')"),
    "brief":     (cmd_brief,     "skip room prose after moves; bare toggles (see 'help formatting')"),
    "config":    (cmd_config,    "prefs by category: config brief|combat|autoloot|full|…"),
    "account":   (cmd_account,   "show/create/link your account (see 'help account')"),
    "alias":     (cmd_alias,     "list, set, or clear your command shortcuts"),
    "prompt":    (cmd_prompt,    "show or set your vitals prompt after each command and combat round"),
    "date":      (cmd_date,      "full calendar date, season, and moon (see 'help calendar')"),
    "bug":       (cmd_bug,       "file a bug report for staff (see 'help bug')"),
    "bugs":      (cmd_bugs,      "list your bug tickets; bugs read / bugs comment (see 'help bug')"),
    "suggest":   (cmd_suggest,   "file a suggestion for staff (see 'help suggest')"),
    "ideas":     (cmd_ideas,     "list your ideas; ideas read / ideas comment (see 'help suggest')"),
    "suggestions": (cmd_ideas,   "list your ideas; ideas read / ideas comment (see 'help suggest')"),
    "typo":      (cmd_typo,      "file a copy typo for staff (see 'help typo')"),
    "typos":     (cmd_typos,     "list your typo tickets; typos read / typos comment (see 'help typo')"),
    "helpsubmit": (cmd_helpsubmit, "propose new help content for staff review (see 'help helpsubmit')"),
    "hedit":     (cmd_hedit,     "GM: hot-edit a help page live, no deploy (see 'gmhelp hedit')"),
    "hrefresh":  (cmd_hrefresh,  "GM: refresh a hedit overlay from static help (see 'gmhelp hrefresh')"),
    "hdelete":   (cmd_hdelete,   "GM: remove a hedit overlay help page (see 'gmhelp hdelete')"),
    "hunder":    (cmd_hunder,    "GM: show git help beneath a hedit overlay (see 'gmhelp hunder')"),
    "hnews":     (cmd_hnews,     "GM: list hedit overlays with fresh git canon (see 'gmhelp hnews')"),
    "reports":   (cmd_reports,   "alias: gm reports -- staff ticket list (see 'gmhelp gm-reports')"),
    "resolve":   (cmd_resolve,   "GM: mark bug/suggestion resolved (optional reason; or open/approved/rejected)"),
    "changes":   (cmd_changes,   "recent changelog (newest 10, listed by #; * = new); type the # to open one; changes search <word>; changes new | changes all; GMs: changes ops | changes ops <n> (help changes)"),
    "commands":  (cmd_commands,  "compact verb list (hubs, not glued aliases); commands here for this room; commands detail for full tips; commands <verb> for one"),
    "mpkg":      (cmd_mpkg,      "install/update the Mudlet HUD package now (mpkg download; see 'help mudlet')"),
    "help":      (cmd_help,      "topic index, or help <topic|command> for one page"),
    "gmhelp":    (cmd_gmhelp,    "GM: staff help -- gmhelp <topic>; gmhelp jargon for internals"),
    "quit":      (cmd_quit,      "disconnect; your body stays as an Echo (see 'help echo')"),
    "logout":    (cmd_logout,    "character select without reconnecting; body stays as an Echo (see 'help logout')"),
}
